# Predicting Clickbait using NLP

## Importing Libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Reading Datasets

In [ ]:
data = pd.read_csv('clickbait_data.csv')

In [ ]:
data.rename(columns = {'clickbait':'label'}, inplace = True)

In [ ]:
len(data)

32000

## Text Preprocessing

In [ ]:
import re
X = []
for title in data['headline']:
  sentence = re.sub('[^a-zA-Z]', ' ', title)
  sentence = sentence.lower()
  sentence = sentence.split()
  sentence = ' '.join(sentence)
  X.append(sentence)



y = data['label']

## Test/Train Split

## Text Representations

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer
cv = CountVectorizer(max_features = 1000)
tfidf = TfidfTransformer(norm=None)
X = cv.fit_transform(X).toarray()
X = tfidf.fit_transform(X).toarray()



In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

## Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)


GaussianNB()

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
cm = confusion_matrix(y_test,classifier.predict(X_test))
print(cm)
accuracy_score(y_test, y_pred)


[[4430  413]
 [ 204 4553]]


0.9357291666666666

## Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(fit_intercept=True, penalty="l2", C=1, max_iter=200 ,solver='saga')
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
cm = confusion_matrix(y_test,classifier.predict(X_test))
print(cm)
accuracy_score(y_test, y_pred)


[[4651  192]
 [ 233 4524]]


/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


0.9557291666666666

## Linear SVM

In [ ]:
from sklearn.svm import LinearSVC
classifier = LinearSVC()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
cm = confusion_matrix(y_test,classifier.predict(X_test))
print(cm)
accuracy_score(y_test, y_pred)

[[4639  204]
 [ 243 4514]]


/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


0.9534375

## Decision Tree

In [ ]:
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
cm = confusion_matrix(y_test,classifier.predict(X_test))
print(cm)
accuracy_score(y_test, y_pred)

[[4396  447]
 [ 395 4362]]


0.9122916666666666