# Predicting Fake News using NLP

## Importing Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Reading Datasets

In [2]:
# dataset 1: news large dataset
true =pd.read_csv('True.csv', delimiter=',')
true['label'] = 1


false =pd.read_csv('Fake.csv', delimiter=',')
false['label'] = 0




In [3]:
data = pd.concat([true, false], axis=0)

In [4]:
data=data.drop(['text','subject','date'], axis=1)

## Text Preprocessing

In [20]:
import re
from nltk.stem.porter import PorterStemmer
X = []
for title in data['title']:
  sentence = re.sub('[^a-zA-Z]', ' ', title)
  sentence = sentence.lower()
  sentence = sentence.split()
  sentence = ' '.join(sentence)
  X.append(sentence)



y = data['label']

## Test/Train Split

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Text Representations

In [8]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer
cv = CountVectorizer(max_features=1000)
tfidf = TfidfTransformer(norm=None)
X = cv.fit_transform(X).toarray()
X = tfidf.fit_transform(X).toarray()



In [ ]:
print(data.head())

## Naive Bayes

In [10]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
cm = confusion_matrix(y_test,classifier.predict(X_test))
print(cm)
accuracy_score(y_test, y_pred)

[[5160  698]
 [ 325 5042]]


0.9088641425389755

## Logistic Regression

In [11]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(fit_intercept=True, penalty="l2", C=1, max_iter=200 ,solver='saga')
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
cm = confusion_matrix(y_test,classifier.predict(X_test))
print(cm)
accuracy_score(y_test, y_pred)


[[5489  369]
 [ 271 5096]]


/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


0.9429844097995546

## Linear SVM

In [12]:
from sklearn.svm import LinearSVC
classifier = LinearSVC()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
cm = confusion_matrix(y_test,classifier.predict(X_test))
print(cm)
accuracy_score(y_test, y_pred)

[[5477  381]
 [ 263 5104]]


/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


0.9426280623608018

## Decision Tree

In [13]:
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
cm = confusion_matrix(y_test,classifier.predict(X_test))
print(cm)
accuracy_score(y_test, y_pred)

[[5388  470]
 [ 627 4740]]


0.902271714922049